title: dmn-cli - A DMN command-line interface
author: Guilherme Carreiro
email: karreiro@gmail.com
description: >
  A command-line interface tool which allows you to easily manage, inspect, and preview DMN models
baseurl: ""
url: "http://dmn-cli.com"
google_analytics: "UA-172676484-1"
markdown: kramdown
